web/router.ex
defmodule Cru.Router do
  use Cru.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Cru do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/services", ServiceController, only: [:show]
  end

  scope "/admin", Cru.Admin, as: :admin do
    pipe_through :browser

    get "/dashboard", DashboardController, :index
    resources "/slides", SlideController
    resources "/services", ServiceController
    resources "/testimonials", TestimonialController
    resources "/products", ProductController
    resources "/clients", ClientController
    resources "/articles", ArticleController
    resources "/messages", MessageController, only: [:index, :show, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", Cru do
  #   pipe_through :api
  # end
end

lib/cru/endpoint.ex
defmodule Cru.Endpoint do
  use Phoenix.Endpoint, otp_app: :cru

  socket "/socket", Cru.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :cru, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_cru_key",
    signing_salt: "1TT8FIph"

  plug Cru.Router
end

lib/cru/repo.ex
defmodule Cru.Repo do
  use Ecto.Repo, otp_app: :cru
end

web/models/article.ex
defmodule Cru.Article do
  use Cru.Web, :model

  schema "articles" do
    field :title, :string
    field :body, :string

    timestamps
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :body])
    |> validate_required([:title, :body])
  end
end

web/models/client.ex
defmodule Cru.Client do
  use Cru.Web, :model

  schema "clients" do
    field :logo, :string
    field :name, :string
    field :body, :string

    timestamps
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:logo, :name, :body])
    |> validate_required([:logo, :name, :body])
  end
end

web/models/message.ex
defmodule Cru.Message do
  use Cru.Web, :model

  schema "messages" do
    field :name, :string
    field :email, :string
    field :phone, :string
    field :body, :string

    timestamps
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name, :email, :phone, :body])
    |> validate_required([:name, :email, :phone, :body])
  end
end

web/models/product.ex
defmodule Cru.Product do
  use Cru.Web, :model

  schema "products" do
    field :icon, :string
    field :title, :string
    field :body, :string
    embeds_many :features, Cru.ProductFeature

    timestamps
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:icon, :title, :body])
    |> validate_required([:icon, :title, :body])
    |> cast_embed(:features)
  end
end

web/models/product_feature.ex
defmodule Cru.ProductFeature do
  use Cru.Web, :model

  # @primary_key {:id, :binary_id, autogenerate: true}
  embedded_schema do
    field :title, :string, default: "title"
    field :body, :string, default: "body"

  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :body])
    |> validate_required([:title, :body])
  end
end

web/models/service.ex
defmodule Cru.Service do
  use Cru.Web, :model

  schema "services" do
    field :icon, :string
    field :title, :string
    field :body, :string
    embeds_one :style, Cru.ServiceStyle

    timestamps
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:icon, :title, :body])
    |> validate_required([:icon, :title, :body])
    |> cast_embed(:style)
  end
end

web/models/service_style.ex
defmodule Cru.ServiceStyle do
  use Cru.Web, :model

  embedded_schema do
    field :color, :string, default: "#444"
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:color])
    |> validate_required([:color])
  end


end

web/models/slide.ex
defmodule Cru.Slide do
  use Cru.Web, :model

  schema "slides" do
    field :title, :string
    field :sub_title, :string
    field :body, :string
    field :link_text, :string
    field :link_url, :string
    embeds_one :style, Cru.SlideStyle

    timestamps
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :sub_title, :body, :link_text, :link_url])
    |> validate_required([:title, :sub_title, :body, :link_text, :link_url])
    |> cast_embed(:style)
  end
end

web/models/slide_style.ex
defmodule Cru.SlideStyle do
  use Cru.Web, :model

  # @primary_key {:id, :binary_id, autogenerate: true}
  embedded_schema do
    field :background_color, :string, default: "#ccc"
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:background_color])
    |> validate_required([:background_color])
  end


end

web/models/testimonial.ex
defmodule Cru.Testimonial do
  use Cru.Web, :model

  schema "testimonials" do
    field :full_name, :string
    field :designation, :string
    field :company, :string
    field :body, :string

    timestamps
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:full_name, :designation, :company, :body])
    |> validate_required([:full_name, :designation, :company, :body])
  end
end

web/controllers/page_controller.ex
defmodule Cru.PageController do
  use Cru.Web, :controller


  def index(conn, _params) do
    slides = Repo.all(Cru.Slide)
    services = Repo.all(Cru.Service)
    testimonials = Repo.all(Cru.Testimonial)
    render conn, "index.html", slides: slides, services: services, testimonials: testimonials
  end
end

web/controllers/service_controller.ex
defmodule Cru.ServiceController do
  use Cru.Web, :controller

  alias Cru.Service

  def show(conn, %{"id" => id}) do
    service = Repo.get!(Service, id)
    render conn, "show.html", service: service
  end
end

web/views/admin/client_view.ex
defmodule Cru.Admin.ClientView do
  use Cru.Web, :view
end

web/views/admin/slide_view.ex
defmodule Cru.Admin.SlideView do
  use Cru.Web, :view
  
end

web/views/error_view.ex
defmodule Cru.ErrorView do
  use Cru.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Cru.LayoutView do
  use Cru.Web, :view
end

web/views/page_view.ex
defmodule Cru.PageView do
  use Cru.Web, :view
end

web/views/service_view.ex
defmodule Cru.ServiceView do
  use Cru.Web, :view
end

web/templates/page/index.html.eex
<div class="slides">
  <%= for slide <- @slides do %>
    <div class="slide slide-<%= slide.id %>" style="color: #fff; background-color: <%= slide.style.background_color %>">
      <div class="container">
        <h1><%= slide.title %></h1>
        <h3><%= slide.sub_title %></h3>
        <p><%= slide.body %></p>
        <p> <%= link slide.link_text, to: slide.link_url, class: "btn btn-secondary-outline" %> </p>
      </div>
    </div>
  <% end %>
</div>
<!-- Slides End -->
<div class="services">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 text-xs-center">
        <h1>Our Services</h1>
        <p style="color:#9e9e9e; ">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis autem laborum totam maiores sunt quas velit esse sed officia nesciunt odit cumque aperiam, at! Perspiciatis, ratione placeat rem quaerat aspernatur!
        </p>
        <br> <br>
      </div>
    </div>
    <div class="row">
      <%= for service <- @services do %>

        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
          <div class="service text-xs-center" style="border-top: 3px solid <%= service.style.color %>;">
            <p><i class="fa fa-<%= service.icon %>" aria-hidden="true" style="margin:20px 0;font-size:40px; color:<%= service.style.color %>"></i></p>
            <h3><%= service.title %></h3>
            <p class="" style="color:#9e9e9e; font-size:13px;"><%= service.body %></p>
            <p><%= link "View More", to: service_path(@conn, :show, service ), class: "btn btn-secondary-outline" %></p>
          </div>
        </div>

        <% end %>
    </div>
  </div>
</div>
<!-- Services End -->
<div class="testimonials_warapper">
  <div class="container">
    <div class="testimonials">
      <%= for testimonial <- @testimonials do %>
        <div class="testimonial testimonial-<%= testimonial.id %>">
          <div class="col-xs-12">
            <p style="background-color: rgba(0,0,0, 0.4); color: rgba(255,255,255,0.6); padding: 30px; border-radius: 5px"><%= testimonial.body %></p>
            <h4><%= testimonial.full_name %></h4>
            <p><%= testimonial.designation %>, <%= testimonial.company %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>